export const BANNERSILDER_LIST = 'BANNERSILDER_LIST';
export const BANNERSILDER_INFO_FORMSTATE = 'BANNERSILDER_INFO_FORMSTATE';
export const BANNERSILDER_ITEM_FORMSTATE = 'BANNERSILDER_ITEM_FORMSTATE';